name: Auto-Format & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write      # ← grants write access for GITHUB_TOKEN

jobs:
  format-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # erlaubt später git push

      - name: Install shfmt
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y shfmt

      - name: Format shell scripts
        shell: bash
        run: |
          shfmt -w -ci -sr .
          find . -type f -name '*.sh' -exec sed -i 's/\t/  /g' {} \;

      - name: Run test suite
        run: bash hangman/tests/run-tests.sh

      - name: Commit formatted code
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "chore: auto-format shell scripts"
            git push
          else
            echo "Nothing to commit, all scripts already formatted."
          fi
